---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cu-du-reconfig.cu-du-reconfig.dcnlab.ssu.ac.kr
  resources:
  - nfreconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cu-du-reconfig.cu-du-reconfig.dcnlab.ssu.ac.kr
  resources:
  - nfreconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - cu-du-reconfig.cu-du-reconfig.dcnlab.ssu.ac.kr
  resources:
  - nfreconfigs/status
  verbs:
  - get
  - patch
  - update
