apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: oai-cu-du-reconfiguration
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
