apiVersion: cu-du-reconfig.cu-du-reconfig.dcnlab.ssu.ac.kr/v1
kind: NFReconfig
metadata:
  labels:
    app.kubernetes.io/name: oai-cu-du-reconfiguration
    app.kubernetes.io/managed-by: kustomize
  name: cucp-regional-sample
  # namespace: oai-ran-cucp
spec:
  clusterInfo:
    - name: regional
      repo: http://192.168.28.111:31650/nephio/regional.git
      clusterType: CUCP
      nfDeployment:
        name: cucp-regional
        namespace: oai-ran-cucp
      targetCluster: #where to migrate the resource to
        name: cluster1-capo
    - name: edge
      repo: http://192.168.28.111:31650/nephio/edge.git
      clusterType: DU
      configRef: #NF DU config --> Config resource
        name: oai-cucp-config
        namespace: oai-ran-du
        nfDeployment: #NF DU config --> NFDeployment resource
          name: du-edge
          namespace: oai-ran-du
    - name: edge
      repo: http://192.168.28.111:31650/nephio/edge.git
      clusterType: CUUP
      configRef: #NF CUUP config --> Config resource
        name: oai-cucp-config
        namespace: oai-ran-cuup
        nfDeployment:   #NF CUUP config --> NFDeployment resource
          name: cuup-edge
          namespace: oai-ran-cuup
  provider: cucp.openairinterface.org
  interfaces:  #CU new node configs NAD
  - name: n2
    hostInterface: ens7
    nameNad: cucp-regional-n2
    namespaceNad: oai-ran-cucp
    ipv4:
      address: 192.168.80.55/24 #CUCP_N2_IP
      gateway: 192.168.80.1 #CUCP_N2_GW
  - name: f1c
    hostInterface: ens9
    nameNad: cucp-regional-f1c
    namespaceNad: oai-ran-cucp
    ipv4:
      address: 192.168.100.21/24 #CUCP_F1C_IP
      gateway: 192.168.100.1 #CUCP_F1C_GW
  - name: e1
    hostInterface: ens8
    nameNad: cucp-regional-e1
    namespaceNad: oai-ran-cucp
    ipv4:
      address: 192.168.110.20/24 #CUCP_E1_IP
      gateway: 192.168.110.1 #CUCP_E1_GW
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  - name: vpc-cudu-f1
    interfaces:
    - f1c
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: cucp-nf-config
    namespace: oai-ran-cucp
  - name: cucp-ran-amf-core
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
    namespace: oai-ran-cucp